# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/apsimxml',
                'doc_host': 'https://DanielKick-USDA.github.io',
                'git_url': 'https://github.com/DanielKick-USDA/apsimxml',
                'lib_path': 'apsimxml'},
  'syms': {'apsimxml.core': {'apsimxml.core.foo': ('core.html#foo', 'apsimxml/core.py')}}}
